package userManager

type Mode int

const (
	MODE_DEFAULT Mode = iota
	MODE_SETLANGUAGE

	MODE_SETUP_LANGUAGE
	MODE_SETUP_TIMEZONE
	MODE_SETUP_POLICY

	MODE_CREATE_EVENTNAME
	MODE_CREATE_EVENTDATE
	MODE_CREATE_EVENTTIME
	MODE_CREATE_EVENTLOCATION
	MODE_CREATE_SETNOTES

	MODE_EDIT_STRING
	MODE_EDIT_NUMBER
	MODE_EDIT_CHOICE
	MODE_EDIT_DATE
	MODE_EDIT_TIME
	MODE_EDIT_PICTURE
	MODE_EDIT_COSTS1
	MODE_EDIT_COSTS2
	MODE_EDIT_PUBLIC

	MODE_GLOBALMSG
	MODE_GLOBALMSGSENDING

	MODE_GUESTS_SET_GUESTS
	MODE_DONATE_CUSTOM

	MODE_LISTNEARBY
	MODE_LISTNEARBYFEED
)
