package userManager

type Mode int

const (
	MODE_DEFAULT Mode = iota
	MODE_SETLANGUAGE

	MODE_SETUP_LANGUAGE
	MODE_SETUP_TIMEZONE
	MODE_SETUP_POLICY

	MODE_CREATE_EVENTNAME
	MODE_CREATE_EVENTDATE
	MODE_CREATE_EVENTTIME
	MODE_CREATE_EVENTLOCATION

	MODE_EDIT_STRING
	MODE_EDIT_NUMBER
	MODE_EDIT_CHOICE
	MODE_EDIT_DATE
	MODE_EDIT_TIME
)
